-
  name:  'Neos - Frontend - Redirect'
  uriPattern: '{path}'
  defaults:
    '@package':    'MOC.Redirects'
    '@controller': 'Redirect'
    '@action':     'redirect'
    '@format':     'html'
  routeParts:
    'path':
      handler:     'MOC\Redirects\Routing\RedirectFrontendNodeRoutePartHandler'
  appendExceedingArguments: TRUE
